- Python/ChatroomApplication/README.md
- Python/ChatroomApplication/client.py
- Python/ChatroomApplication/server.py
* Added server.py which is the script to be run on the server
* Added client.py which is to be used by user which connects to the server.
* Added readme.md which describes the project in brief.
> Created a chatroom application using python

- JAVA/Practice_Problems/Anagrams.java
- JAVA/Practice_Problems/Binary_Addition.java
- JAVA/Practice_Problems/Break_Word.java
- JAVA/Practice_Problems/Longest_Palindrome_substring.java
- JAVA/Practice_Problems/Max_Product_Subarray.java
- JAVA/Practice_Problems/Next_Permutation.java
- JAVA/Practice_Problems/Pascal's_Triangle.java
- JAVA/Practice_Problems/Regular_Expression_Matching.java
- JAVA/Practice_Problems/Remove_Element.java
- JAVA/Practice_Problems/ReverseWord_String.java
- JAVA/Practice_Problems/Solving_Sudoku.java
- JAVA/Practice_Problems/Sort_List.java
- JAVA/Practice_Problems/Valid_Number.java
- JAVA/Practice_Problems/Valid_Parentheses.java
- JAVA/Practice_Problems/Word_Search.java
> Added some .java files in JAVA/Practice_Problems

- Python/TicTacToe with minimax algorithm/README.md
- Python/TicTacToe with minimax algorithm/TicTacToe using Minimax/Tic_Tac_Toe-Tkinter_Gui.py
A python 'tkinter' GUI based application for the game of TicTacToe. 
Uses minimax algorithm.
> Python GUI application for the game TicTacToe

- C and C++/sumofarray.cpp
> Sum of all the elements of the array

- Python/Dijkstras.py
added dijkstras shortest path finding algorithm in Python directory.
> added dijkstras algorithm [Python]

- C and C++/Competitive Problem Solutions/CodeChef/ADAKING.cpp
Description: Codechef ADAKING problem solved.
> ADAKING problem solved

- C and C++/Competitive Problem Solutions/Leetcode/LinkedList2.cpp
- C and C++/Competitive Problem Solutions/Leetcode/PalindromLinkedList.cpp
- C and C++/Competitive Problem Solutions/Leetcode/SplitStringinBalancedStrings.cpp
- C and C++/Competitive Problem Solutions/Leetcode/UniqueMorseCodeWords.cpp
Added some of leetcode problem solutions for cpp
> Add leetcode questions

- JAVA/Practice_Problems/Climbing_Stairs.java
- JAVA/Practice_Problems/Closest_Sum.java
- JAVA/Practice_Problems/Find_missingpositive.java
- JAVA/Practice_Problems/Gray_Code.java
- JAVA/Practice_Problems/Peak_Element.java
Please review this too. Thank You  : )
> added few more java programs

- HTML/readme.md
Originally, the readme of Html file was about Java, so I changed it to the description about Html in the CONTRIBUTION branch only. Accept it if you find this PR useful.
> Updated Readme.md

- Kotlin/ElectronicShop.kt
Contributing for hacktoberfest 2020
> Add ElectronicShop Solution kotlin

- C and C++/01Knapsack.c
Dynamic 01 Knapsack Algorithm implemented in C lanuage
> 01_Knapsack

- HTML/button-hover.html.html
- HTML/style2.css
I added some button hover effects using HTML/CSS.
> added some button hover effects

- JAVA/Practice_Problems/Array Sum.java
> Create sum of Array .java

- Python/jarvis.py
jarvis - a virtual assistant written in python , it is able to recognize voice and deliver the tasks . python modules such pyttsx3 , python text to speech , speechRecognition , pyAudio are used /
>  implemented jarvis - a virtual desktop assistant

- CONTRIBUTING_BEGINNER.md
- CONTRIBUTING_INTERMEDIATE.md
- README.md
Edited the "CONTRIBUTING_BEGINNER.md" file by incorporating some grammatical corrections.
> README-edits

- JAVA/ArrayQueue.java
- JAVA/Tree.java
> Array Queue in Java

- HTML/VeggieBurger.html
A minimal Veggie Burger component which can be used instead of the conventional Hamburger.
> Created a Veggie Burger compenent in HTML/CSS

- C and C++/elementofarrayatspecifiedposition.cpp
Element of array at a specified location
> Finding the element of an array at a particular location

- Python/simpleCalculator.py
Added a Simple Python Calculator Program!
> Added simpleCalculator.py Program

- Python/DS_ALGO/LinkedList(all_operation).py
Updated the DS algo with the likedlist operation using python.
> Added Linkedlist.py All Operation

- JAVA/Remove_WORD.java
**In this program we input a string (sentence) from the user and accept the word position of the word which is to be deleted. If the position is an invalid one then suitable message will be displayed else the modified sentence will be shown. The outputs are also given at the end of the code.**
> Remove a word from the string by accepting the position from user.

- C and C++/Competitive Problem Solutions/HackerRank/Templates.cpp
Added solution to "Templates.cpp" problem in newly created HackerRank Folder.
> HackerRank additions

- Python/multiplication_table.py
It makes using simple for loop.
When you run the code, the program asks a number from a user that you want to show the multiplication table.
Here, I am attaching the output.
> Create a Multiplication Table

- Python/hangman.py
A simple hangman game written in Python.
> Added a hangman game file to Python

- JAVA/DuplicateBrackets.java
This is the problem of Stack 
in which you have to check the duplicate Brackets.
> Duplicate Brackets

- JAVA/HappyNumber.java
This is a very famous problem of hashmap.
> Happy number

- JAVA/LineNumbering.java
Sample input :
Hello world
I am a file
Read me until end-of-file.
Sample output:
1 Hello world
2 I am a file
3 Read me until end-of-file.
> This will add numbers for each line provided by user.

- C and C++/reverse_digit.cpp
please add this....this is my first pull request..
> reverse_digit.cpp

- C and C++/EditDistance(DP).cpp
- C and C++/LongestIncSubsequence(DP).cpp
- C and C++/N-Queen.cpp
- C and C++/PRIMS.CPP
Adding important Graph and Dynamic Programming algorithms along with comments
> adding many new algorithms

- C and C++/binaryconvo.c
This program is used to convert a decimal number to binary . It is useful to beginners.
> BinaryConverter

- C and C++/maximumsubarraysum.cpp
Finding a sub array with maximum sum
> Finding Maximum Sub Array Sum

- print's table of any number
> Create print's table of any number

- C and C++/treeImplementation.cpp
I have added Binary Search Tree Implementation with c++
including delete node, search node, add a node, the height of node function, and traversal functions.
Thanks for a chance.
> added tree implementation in c++

- JAVA/SingleNumber.java
> Single Number

- GetCommon1.java
> Common Number

- JAVA/matrixComputation.java
A user driven menu based program for addition, multiplication and transpose of matrices.
> Menu based java program for matrices

- C and C++/validity_of_parenthesis.cpp
Added a program that checks whether a parenthesis expression is valid or not.
Example :
1. {{()}}-Valid
2. {({)}}-Inavlid
> added valid parenthesis expression checker

- JAVA/SumOfNumber.java
> SumOfNumber.java is added

- Python/mapit.py
SImple python script to launch google maps with a place diectly from terminal
> uploaded mapit.py

- C and C++/QuickSort.cpp
@rishabhgupta03 I have contributed by adding Quick Sort in C++. Check it out and if you find everything fine please merge it.
> Added Quick Sort in C++

- Solution.java
- Staircase.java
A program that prints a staircase of size n
> Staircase Program

- Python/Face_Detection/Face_detection_Code/Face Detect.py
- Python/Face_Detection/Face_detection_Code/Requirement.txt
- Python/Face_Detection/Face_detection_Code/haarcascade_frontalface_default.xml
A program for Face Detection using OpenCV and Haarcascade , Puts a rectangular box around the face when Detected .
> Face Detection using OpenCV and Haarcascade

- C and C++/PDF Viewer.cpp
- JAVA/Diagonal Diff. of Matrix.java
- JAVA/Median of list of nos..java
> Absolute diff. between the sums of its diagonals.

- C and C++/Competitive Problem Solutions/CodeChef/CRDGAME3.cpp
- C and C++/Competitive Problem Solutions/CodeChef/LINCHESS.CPP
Added CODECHEF Aug 2020 challenge questions
1. LINCHESS
2. CRDGAME3
> Added CODECHEF Aug 2020 challenge questions

- Python/Pascal-Triangle.py
Pascal Triangle Program in Python3.
> Pascal-triangle-Python

- JAVA/KadaneProblem.java
- JAVA/MazeProblem.java
#5 Created 2 java files(kadaneProblem and MazeProblem) under java folder. Added my experience to hacktoberfest.
> added two popular java programs

- C and C++/Competitive Problem Solutions/Leetcode/RomanToInteger.cpp
Please let me know if any changes are required.
> Added RomanToInteger.cpp LeetCode solution

- JAVA/Apple and Orange Problem.java
Sam's house has an apple tree and an orange tree that yield an abundance of fruit. We have to determine the number of apples and oranges that land on Sam's house. The value of apples and  oranges are given. We have to determine how many apples and oranges will fall on Sam's house
> Apple and Orange Problem

- JAVA/AverageMarks.java
Make use of Streams and Lambdas to achieve functional programming
> Use Functional Style Java Programming

- C and C++/matrix_mul.cpp
created a program to multiply matrices in cpp.
> matrix_mul.cpp

- JAVA/MagicSquare.java
1. Here we are  given  a magic square which is a n x n  matrix of distinct positive integers from 1 to n ^2  where the sum of any row, column, or diagonal of length n is always equal to the same number: the magic constant.     
2. Here we are given a 3 x 3 matrix s of integers in the inclusive range[1,9] . We can convert any digit a to any other digit b in the range  [1,9]  at cost of  |a-b|. Given s, we have to  convert it into a magic square at minimal cost and  print this cost on a new line.
> Magic Square Problem

- JAVA/Dice.java
Java code for roll n times n side Dices
> Java Dice roller

- C and C++/Competitive Problem Solutions/Leetcode/kth symbol grammar leetcode problem.cpp
leetcode problem using recursion
> Create kth symbol grammar leetcode problem.cpp

- C and C++/Competitive Problem Solutions/Codeforces/Calculate the area.cpp
- C and C++/Competitive Problem Solutions/Codeforces/Candies.cpp
- C and C++/Competitive Problem Solutions/Codeforces/Matryoshka_Dolls.cpp
- C and C++/Competitive Problem Solutions/Codeforces/Yet_Another_Pallindrome_problem.cpp
> CF solutions added

- vigenere.py
#119 Issue resolved. @rishabhgupta03
> Vigenere Cipher in Python 

- JAVA/leapyear.java
Hey There,
I just added a java program in java folder to check whether a year is leap year or not....Hope you will like it..:)
> Added a new java program for leap year finder

- .classpath
- .project
- Competitive Coding/DS/Arrays/WaveTraversal2D.java
> Wave Traversal of an 2D array

- Competitive Coding/DS/strings/Substring_removal_game.cpp
Contributed competitive programming question-Substring removal game
> Substring removal game-Competitive Programming

- C and C++/Floyd warshall.cpp
Problem Floyd Warshall
language used: C++
> Added Floyd warshall.cpp
